// Runtime environment variables for CyberGuard Frontend
// Auto-generated by generate-env.js — DO NOT EDIT DIRECTLY
window.__ENV__ = Object.freeze({
  "API_BASE_URL": "http://localhost:3001",
  "PORT": "3000",
  "GENERATED_AT": "2026-09-21T05:10:38.090Z"
});
