// Script to generate env.js for the frontend from .env or process.env
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function loadEnvFile(filePath) {
  const envVars = {};
  if (!fs.existsSync(filePath)) return envVars;
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx !== -1) {
        const key = trimmed.slice(0, eqIdx).trim();
        let val = trimmed.slice(eqIdx + 1).trim();
        // Strip outer quotes if present
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        envVars[key] = val;
      }
    }
  } catch (err) {
    console.warn(`[generate-env] Warning loading ${filePath}:`, err.message);
  }
  return envVars;
}

// Check local .env first, then parent .env
const localEnvPath = path.join(__dirname, '.env');
const parentEnvPath = path.join(__dirname, '..', '.env');

const localVars = loadEnvFile(localEnvPath);
const parentVars = loadEnvFile(parentEnvPath);

// Prioritize process.env (e.g. Vercel/Render env vars), then local .env, then parent .env
const apiBase =
  process.env.API_BASE_URL ||
  process.env.BACKEND_URL ||
  process.env.VITE_API_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  localVars.API_BASE_URL ||
  localVars.BACKEND_URL ||
  parentVars.API_BASE_URL ||
  parentVars.BACKEND_URL ||
  '';

const port =
  process.env.PORT ||
  localVars.PORT ||
  '3000';

const appName =
  process.env.APP_NAME ||
  localVars.APP_NAME ||
  parentVars.APP_NAME;

const clientEnv = {
  API_BASE_URL: apiBase,
  PORT: port,
  APP_NAME: appName,
  GENERATED_AT: new Date().toISOString()
};

const fileContent = `// Runtime environment variables for CyberGuard Frontend
// Auto-generated by generate-env.js — DO NOT EDIT DIRECTLY
window.__ENV__ = Object.freeze(${JSON.stringify(clientEnv, null, 2)});
`;

const outputPath = path.join(__dirname, 'env.js');
fs.writeFileSync(outputPath, fileContent, 'utf-8');

// Ensure public/ output directory exists for Vercel
const publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}
fs.writeFileSync(path.join(publicDir, 'env.js'), fileContent, 'utf-8');


const assetSrc = path.join(__dirname, 'nuclei-dashboard.webp');
if (fs.existsSync(assetSrc)) {
  fs.copyFileSync(assetSrc, path.join(publicDir, 'nuclei-dashboard.webp'));
}

console.log(`[generate-env] Generated env.js and synchronized public/ output with API_BASE_URL: "${apiBase || '(Dynamic origin fallback)'}"`);
